# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Piece-Month
version:      1.00
version_from: lib/Time/Piece/Month.pm
installdirs:  site
requires:
    Time::Piece::Range:            0.9

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
